#!/usr/bin/env expect

set timeout 60
spawn create-remix fresh-app
while 1 {
  expect {
    "  Vercel" { send -- "\033\[B" }
    "❯ Vercel" { send -- "\r"; break }
  }
}
expect "TypeScript"
send -- "\r"
expect "npm"
send -- "n\r"
expect "README"