#!/usr/bin/env expect

set timeout 60
spawn yarn create t3-app fresh-app
expect "TypeScript"
send -- "\r"
expect "nextAuth"
send -- "a\r"
expect "repository?"
send -- "\r"
expect "install"
send -- "\r"
expect "steps"
