#!/usr/bin/env expect

set timeout 60
spawn yarn create svelte fresh-app
expect "template"
send -- "\r"
expect "TypeScript"
send -- "\033\[B\r"
expect "ESLint"
send -- "\033\[C\r"
expect "Prettier"
send -- "\033\[C\r"
expect "Playwright"
send -- "\033\[C\r"
