name: Update docs
on:
  push:
    branches:
      - 'main'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: node update-docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update project list
          file_pattern: docs/modules/ROOT/partials/projects.adoc
          commit_user_name: dtinth-bot
          commit_user_email: dtinth-bot@users.noreply.github.com
          commit_author: dtinth-bot <dtinth-bot@users.noreply.github.com>
