name: Factory
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        generator:
          - fresh-cypress-project
          - fresh-next-app
          - fresh-next-app-typescript
          - fresh-react-app
          - fresh-react-app-typescript
          - fresh-redwood-app
          - fresh-redwood-app-typescript
          - fresh-remix-app
          - fresh-remix-app-vercel
          - fresh-rush-monorepo
          - fresh-tsdx-lib
          - fresh-tsdx-react-component
          - fresh-tsdx-react-component-with-storybook
          - fresh-vite-app-lit-element-ts
          - fresh-vite-app-lit-element
          - fresh-vite-app-preact-ts
          - fresh-vite-app-preact
          - fresh-vite-app-react-ts
          - fresh-vite-app-react
          - fresh-vite-app-svelte-ts
          - fresh-vite-app-svelte
          - fresh-vite-app-vue-ts
          - fresh-vite-app-vue
          - fresh-vite-app
          - fresh-vite-app-ts
          - fresh-vscode-extension
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: runner
          load: true
          tags: factory-runner
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn node run ${{ matrix.generator }}
      - run: yarn node provision ${{ matrix.generator }}
        env:
          GH_PUSH_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - run: bash sync.sh
        env:
          GH_PUSH_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
