name: Linting

on:
  push: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '20'
      - run: pnpm install
      - run: pnpm tsc
