name: Tidy

on:
  push: {}

jobs:
  tidy:
    name: Ensure codebase is tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '20'
      - run: pnpm install
      - run: pnpm prettier --write .
      - run: git add --update
      - uses: dtinth/patch-generator-action@main
